#!/bin/bash

: "
Lemonbar Wiget Definitions
"

Format()
{
    echo "%{+u}%{B$background} $1 %{B}%{-u}"
}

Clock()
{
    # Define clock
    # format=${1:-"%a %b %d, %T"}
    # DATETIME=$(date "+$format")
    DATE=$(date +"%d/%m/%y")
    TIME=$(date +"%I:%M:%S")

    # printf "$DATETIME"
    # echo "$DATETIME"
    Format "${DATE} {$TIME}"
}

Battery() 
{
    # Requires package 'acpi' for Battery reading
    BAT_PERC=$(acpi --battery | cut -d ',' -f2)

    # echo "$BAT_PERC"
    Format "$BAT_PERC"
}

ActiveWindow()
{
    # printf " $(xdotool getwindowfocus getwindowname)"
    curr_window=$(xdotool getwindowfocus getwindowname)
    if [[ ! "$curr_window" == "" ]]; then
        Format " $(xdotool getwindowfocus getwindowname)"
    else
        echo ""
    fi
}

Workspaces()
{
    desktops=$(bspc query -D --names)
    focused=$(bspc query -D --names -d focused)

    # Loop through all nodes
    for desktop in $desktops; do
        desktop=$(echo "$desktop")
        nodes=$(bspc query -N -d $desktop)

        if [[ ! -z "$nodes" ]]; then
            desktops=$(echo $desktops | sed "s/$desktop/%{F#ff0000}$desktop%{F-}/")
        fi
    done

    desktops=$(echo $desktops | sed "s/$focused/%{B$background}%{+u}_$focused\_%{-u}%{B-}/")

    echo $desktops | sed "s/_/ /g"
}

Packages()
{
    Format "$(sudo pacman -Qu | wc -l)"
}


