#! /bin/sh

# Autostart #
pgrep -x sxhkd > /dev/null || sxhkd & # X Hotkey Daemon
~/personal/scripts/lemonbar/lemonlaunch & # Status Bar

# Monitors #
# bspc monitor Virtual-1 -d I II III IV V VI VII VIII IX X
bspc monitor -d 1 2 3 4 5 6 7 8 9 10

# BSPC Configurations #

## Windows ##
bspc config border_width        2
bspc config window_gap          20

## Positioning ##
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true


