#!/bin/bash
: "
A generic, non-dependent Scratchpad utility for any graphical environment, using xdotools

Many thanks to : 
    - Jake@Linux' Idea and scripting explanation for xdotool's window-in and window-out functionality in the video [Scripts to allow Window Manager agnostic scratchpads]

Dependencies:
    - xdotools
"

argv=$@ # Optional Arguments start in either '-' or '--'
argc="${#argv[@]}"

window_hide()
{
    : "
    - Check for a window name that is provided by the user
    - Check that the window is visible
    - If the window is visible, hide it
    "
    echo "Hide : $1"
    xdotool search --onlyvisible --name $1 windowunmap
}

window_show()
{
    : "
    - Check for a window name that is provided by the user
    - If it exists, show it
    "
    echo "Show : $1"
    xdotool search --name $1 windowmap
}

main()
{
    : "
    Optional Arguments are in the form of
        -opt : Short Form
        --option : Long Form    
    "
    terminal="${1:-$TERM}"
    window_name=$2
    args=${@:3} # Take all arguments pass the first argument
    command="$terminal $args"

    # Set Title
    case "$terminal" in
        "alacritty")
            command="alacritty -t $window_name"
            ;;
        "kitty")
            command="kitty -T $window_name"
            ;;
        *)
            # Default, system command
            # Run in background
            command=""
            ;;
    esac

    # Set Spacing
    command+=" "

    # Set Command
    command+="$args"

    echo $command >> /tmp/dev.log
    
    window_hide "$window_name" || \
        window_show "$window_name" || \
        $command & 
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    main $@
fi
