#!/bin/bash

: "
Lemonbar Driver Script
"

# Kill all lemon-related scripts
killall -q lemonbar
killall -q lemonconfig

declare -A LEMON_COLORS=(
    [light-blue]="#268bd2"
    [grey]="#FF222222"
    [grey-transparent]="#FF22222200"
    [white]="#FFFFFFFF"
)

main()
{
    ### Variables ###

    ## System Information
	curr_monitor_resolution=`xrandr | grep 'primary' | cut -d ' ' -f4 | cut -d '+' -f1 | cut -d ' ' -f4`
    curr_width=`echo "$curr_monitor_resolution" | cut -d 'x' -f1`
    curr_height=`echo "$curr_monitor_resolution" | cut -d 'x' -f2`
    
    ## Local Variable
    width=$curr_width
    height=32
   
    # Runner
    $(dirname $0)/lemonconfig | lemonbar -p \
        -g ${width}x${height}+0+0 \
        -F "${LEMON_COLORS["white"]}" \
        -B "${LEMON_COLORS["grey-transparent"]}" \
        -U "${LEMON_COLORS["light-blue"]}" \
        -u 3 \
        -o -4 \
        -f "JetBrains Mono Medium"-14 \
        -o -2 \
        -f "Hack Nerd Font"-18 | $SHELL
}


if [[ "${BASH_SOURCE[0]}" == ${0} ]]; then
    main "$@"
fi
