#!/bin/env bash

: "
All files to Source
"

# Define Source List
sources=(
    ~/personal/scripts/lemonbar/lemonhelpers
)

# Source files
for file in "${sources[@]}"; do
    if [[ -f "$file" ]]; then
        source $file
    fi
done
